logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

#puerto 8590
server:
    port: 8590
spring:

    application:
        name: api-Gateway
    profiles:
      active: cors


    sleuth:
      propagation:
        type: w3c
      trace-id128: true
      supports-join: false

    cloud:
      gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins:
                - "http://localhost:4200"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders:
                - "Origin"
                - "Access-Control-Allow-Origin"
                - "Content-Type"
                - "Accept"
                - "Jwt-Token"
                - "Authorization"
                - "Origin, Accept"
                - "X-Requested-With"
                - "Access-Control-Request-Method"
                - "Access-Control-Request-Headers"
                - "Access-Control-Allow-Origin"
                - "Access-Control-Allow-Credentials"
                - "Filename"
                - "AUTHORIZATION"
              allowCredentials: true
        discovery:
          locator:
            enabled: true
    zipkin:
        base-url: http://localhost:9411

web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: "GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD"
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"

eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.111:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970